# verify-links.ps1
#
# Checks that every internal link referenced across location pages
# resolves to an actual .php file in the project root.
#
# Checks:
#   1. Country hub URLs generated by loc-section.php breadcrumbs
#      (every page that has a comma in its title links to /ui-ux-design-agency-in-{country})
#   2. Hardcoded links inside individual pages (href="/ui-ux-design-agency-in-...")
#
# Usage:
#   .\verify-links.ps1
#   .\verify-links.ps1 -Verbose    (shows OK links too)
#   .\verify-links.ps1 -Fix        (creates stub pages for missing links)

param(
    [switch]$Verbose,
    [switch]$Fix
)

$rootDir  = "C:\xampp\htdocs\UX_Pacific"
$baseSlug = "ui-ux-design-agency-in-"
$broken   = @()
$ok       = 0

Write-Host ""
Write-Host "UX Pacific - Internal Link Verifier"
Write-Host ("-" * 48)
Write-Host ""

# -- 1. Country breadcrumb links --
# For every state/city page (title contains comma), loc-section.php generates:
#   /ui-ux-design-agency-in-{country}
# We verify that file exists.

Write-Host "Checking country hub links from breadcrumbs..."

$locFiles = Get-ChildItem "$rootDir\$baseSlug*.php" -File
$countryLinks = @{}

foreach ($f in $locFiles) {
    $lines = Get-Content $f.FullName -TotalCount 60 -ErrorAction SilentlyContinue
    $titleLine = $lines | Where-Object { $_ -match '\$pageTitle\s*=\s*' } | Select-Object -First 1
    if (-not $titleLine) { continue }

    if ($titleLine -match "in (.+?)\s*\|") {
        $locPart = $matches[1].Trim()
        if ($locPart -match ',') {
            $country = ($locPart -split ',')[-1].Trim()
            $slug = $country.ToLower() -replace '[^a-z0-9]+', '-'
            $slug = $slug.Trim('-')
            $countryLinks[$slug] = $country
        }
    }
}

foreach ($slug in ($countryLinks.Keys | Sort-Object)) {
    $targetFile = "$rootDir\${baseSlug}${slug}.php"
    if (Test-Path $targetFile) {
        $ok++
        if ($Verbose) { Write-Host "  [OK]     /ui-ux-design-agency-in-$slug" -ForegroundColor Green }
    } else {
        $broken += [PSCustomObject]@{
            Type    = 'Country Hub'
            Link    = "/ui-ux-design-agency-in-$slug"
            File    = "${baseSlug}${slug}.php"
            Country = $countryLinks[$slug]
            Source  = 'loc-section.php (breadcrumb)'
        }
        Write-Host "  [MISS]   /ui-ux-design-agency-in-$slug  ($($countryLinks[$slug]))" -ForegroundColor Yellow
    }
}

# -- 2. Hardcoded links in individual pages --
Write-Host ""
Write-Host "Checking hardcoded internal links in location pages..."

foreach ($f in $locFiles) {
    $content = Get-Content $f.FullName -Raw -ErrorAction SilentlyContinue
    if (-not $content) { continue }

    $matches2 = [regex]::Matches($content, 'href="(/ui-ux-design-agency-in-[a-z0-9\-]+)"')
    foreach ($m in $matches2) {
        $link   = $m.Groups[1].Value
        $slug2  = $link.TrimStart('/')
        $target = "$rootDir\${slug2}.php"

        if (Test-Path $target) {
            $ok++
            if ($Verbose) { Write-Host "  [OK]     $link  ($($f.Name))" -ForegroundColor Green }
        } else {
            $broken += [PSCustomObject]@{
                Type    = 'Hardcoded Link'
                Link    = $link
                File    = $slug2 + '.php'
                Country = ''
                Source  = $f.Name
            }
            Write-Host "  [MISS]   $link  (in $($f.Name))" -ForegroundColor Yellow
        }
    }
}

# -- 3. Summary --
$brokenCount  = $broken.Count
$uniqueBroken = $broken | Select-Object -ExpandProperty File -Unique

Write-Host ""
Write-Host ("=" * 48)
Write-Host "Link verification complete"
Write-Host ("-" * 48)
Write-Host ("  OK links            : {0}" -f $ok)
Write-Host ("  Broken links        : {0}" -f $brokenCount)
Write-Host ("  Unique missing files: {0}" -f $uniqueBroken.Count)
Write-Host ("-" * 48)

if ($brokenCount -gt 0) {
    $grouped = $broken | Group-Object File | Sort-Object Name
    Write-Host ""
    Write-Host "Missing files needed:"
    foreach ($g in $grouped) {
        $refs = $g.Count
        Write-Host ("  -> {0,-60} ({1} ref{2})" -f $g.Name, $refs, $(if ($refs -gt 1) {'s'} else {''}))
    }

    $csvPath = "$rootDir\broken-links-report.csv"
    $broken | Export-Csv -Path $csvPath -NoTypeInformation -Encoding UTF8
    Write-Host ""
    Write-Host "  Full report saved: broken-links-report.csv"

    if ($Fix) {
        Write-Host ""
        Write-Host "Creating stub pages for missing files..." -ForegroundColor Cyan
        $created = 0
        foreach ($slug2 in $uniqueBroken) {
            $target = "$rootDir\$slug2"
            if (Test-Path $target) { continue }

            $locSlug = $slug2 -replace '^ui-ux-design-agency-in-', '' -replace '\.php$', ''
            $locName = (Get-Culture).TextInfo.ToTitleCase($locSlug -replace '-', ' ')

            $stub = @"
<?php
require_once __DIR__ . '/includes/cms_repository.php';
`$countrySlug       = '$locSlug';
`$featuredProjects  = get_published_projects('all', true);
`$ecosystemHomeItems = get_published_ecosystem();
function home_image_url(?string `$url): string {
  `$url = trim((string) `$url);
  if (`$url === '') return uxp_normalize_stored_media_url('img/ux.webp');
  if (preg_match('#^https?://#i', `$url)) return `$url;
  return uxp_normalize_stored_media_url(`$url);
}
`$pageTitle    = 'UI UX Design Agency in $locName | UX Pacific';
`$pageDesc     = 'UX Pacific delivers expert UI/UX design services in $locName.';
`$canonicalUrl = 'https://www.uxpacific.com/ui-ux-design-agency-in-$locSlug';
`$ogTitle      = `$pageTitle;
`$ogDesc       = `$pageDesc;
`$ogUrl        = `$canonicalUrl;
`$currentPage  = 'Home';
`$geoPage = uxp_geo_page(`$countrySlug);
if (`$geoPage) {
  if (!empty(`$geoPage['page_title']))       { `$pageTitle = `$geoPage['page_title']; `$ogTitle = `$pageTitle; }
  if (!empty(`$geoPage['meta_description'])) { `$pageDesc  = `$geoPage['meta_description']; `$ogDesc = `$pageDesc; }
}
?>
<!DOCTYPE html><html lang="en"><head><?php include 'includes/head.php'; ?></head><body>
<?php include 'includes/navbar.php'; ?>
<div class="hero-wrapper" style="position:relative;overflow:hidden"><canvas id="interactive-canvas" style="position:absolute;top:0;left:0;width:100%;height:100%;z-index:0;"></canvas><div class="custom-cursor"></div><section class="hero"><h1 id="heading">WE CRAFT UX THAT MAKES THEM<br /><span style="font-weight:200">STAY, ENGAGE, <span style="font-weight:800">AND</span> CONVERT.</span></h1><p class="subtext">Designing Experiences, Not Just Interfaces</p><br /><a class="btn-primary" href="#" data-bs-toggle="modal" data-bs-target="#auditModal" style="width:210px;height:42px;margin-top:0;padding-left:27px;">Book a UX Audit <span class="arrow"> </span></a></section></div>
<div class="ux-content mt-5 mb-3"><h3 class="ux-subtitle" style="margin-top:50px">About Us <span class="ux-line"> </span></h3><h2 class="ux-title">Where Strategy Meets <span class="highlight"> Stunning </span> Design</h2><p class="ux-description">We're a creative UX/UI design studio passionate about building human-centered digital products.</p><a class="view-more" href="/about"> View More &rarr; </a><br /></div>
<?php include 'includes/loc-section.php'; ?>
<?php include 'includes/footer.php'; ?>
<?php include 'includes/scripts.php'; ?>
</body></html>
"@
            Set-Content -Path $target -Value $stub -Encoding UTF8
            $created++
            Write-Host ("  [STUB]   $slug2") -ForegroundColor Cyan
        }
        Write-Host "  Created $created stub pages."
    } else {
        Write-Host ""
        Write-Host "  Run with -Fix to auto-create stub pages for all missing files."
    }
}

Write-Host ("=" * 48)
Write-Host ""
